spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: ylmn750716
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3s
#  web:
#    resources:
#      static-locations:  [classpath:/hha/]  (改变静态路径）
#  mvc:
#    static-path-pattern: /res/**  （增加静态前缀）

#配置mybatis的规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml #全局配置位置 (但一般配置可以直接写在yaml文件中 全局配置文件就可以删掉了
  mapper-locations: classpath:mybatis/mapper/*.xml  # sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

